Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 10:30:59.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 10:32:26.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 10:32:33.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 10:37:16.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 10:43:50.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 10:46:01.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 13:08:03.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 13:43:30.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
Info:     Reading NASTRAN from C:/Project/CAEAgents/test_cases/cbush_test.bdf using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\nastran.exe on 04-15-2025 14:09:58.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Sensors.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Ddvals.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Directmatrixinputs.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Analysisparameters.
Info:     Processing Parameters.

Warning:  Duplicate Components with ID 1 were found
          Resolution:  Components data will be merged
Warning:  Duplicate Components with ID 2 were found
          Resolution:  Components data will be merged
Summary:  Feinput finished with 0 errors and 2 warnings.
Info:     Translation Complete.
